### ISSUE TITLE
Localization Editor Layout

### ISSUE THREAD

**Issue by michbarsinai** [wolfj123/PolicyModelsPlugin#15]
Generally speaking the layout is good, but could be improved:

- [x] Preview should be moved to a column after the edit fields. This way, the answer names in the previews language are aligned with those in the edited language. Very useful for translation.
- [x] It is OK for the editor to take all views space. There seems to be a max-width there somewhere.
- [x] Can drop the ` :` after the entry name. It's not needed in a GUI.
- [x] When editing answers.txt, the left editor is not Markdown. It's just text.
- [x] Is the answer list updated when new answers are added to the model?
- [x] If an answer is present in the edited localization, but not in the model, a warning sign should appear

**Comment by ofirbed** [comment]
Few questions:
> Preview should be moved to a column after the edit fields

Do you mean to align the editor and the preview in `space.md` and `section.md` files?
> When editing answers.txt, the left editor is not Markdown. It's just text.

Do you want me to remove the current editor? this is not mark down editor- its just a more friendly and comfortable editor for the specific `answer.txt` file. I think we should keep it but its your call.

>Is the answer list updated when new answers are added to the model?
 >If an answer is present in the edited localization, but not in the model, a warning sign should appear

We are planning to call the update method from the DataTags CLI in the beginning of each session (when starting using the localization system), and present the result to the user. So as far as I know, new answers will be added to `answer.txt`  and the irrelevant answer will be presented to the user.

**Comment by michbarsinai** [comment]
> Do you mean to align the editor and the preview in `space.md` and `section.md` files?

This refers to the answers editor. See attached image.

> When editing answers.txt, the left editor is not Markdown. It's just text.

I agree that it's very convenient. This remark refers to a label over the text editors (marked "A" in the image below).

> In the answer list...

That sounds reasonable. The question is, is there a way for the user to know that an answer is no longer relevant (as in, does not appear in the questionnaire anymore). The CLI offers a command called `\loc-diff <localization name>` that lists irrelevant answers, as well as other differences between a localization and a model.

![image](https://user-images.githubusercontent.com/1938468/82747507-1de48600-9da2-11ea-966e-33ba89d2b8dd.png)
