### ISSUE TITLE
Readme.md should just be regular Markdown

### ISSUE THREAD

**Issue by michbarsinai** [wolfj123/PolicyModelsPlugin#16]
No need to create any special editor there, VSCode does a good enough job there.

**Comment by ofirbed** [comment]
Im not getting what you mean here exactly. What is the difference between the `Readme.md` and other .md files? the user shouldnt edit it?

**Comment by michbarsinai** [comment]
The only special `.md` files are `space.md` and `sections.md`. The rest are just regular markdown files.

**Comment by ofirbed** [comment]
Ok. The reason I'm confused is that the `readMe.md` editor is just like the rest of the .md files (except the special ones). So I cant see the change here. Im missing something?

**Comment by michbarsinai** [comment]
With the version I currently have, README.md seems to open as a localization file, rather than Markdown. It should be markdown.

![image](https://user-images.githubusercontent.com/1938468/82747585-24273200-9da3-11ea-8956-23be61bd9331.png)

**Comment by ofirbed** [comment]
Sorry still dont get it. Do you want that the user could not edit the readme.md file? just watch it as a markdown and that's all?
Currently, if you want to translate readme.md, you can open it with the localization system, edit it, and watch it in any other language you want. Actually there is no difference at all other regular .md file in the language folder. 
![image](https://user-images.githubusercontent.com/26577853/82799775-42fcf580-9e83-11ea-811b-6e330db20d36.png)

Can you explain me again what exactly do you expect?  thanks

**Comment by michbarsinai** [comment]
That's great. But when I open the readme.md file directly, it is not opened as markdown, but as a "localization" file (see my previous screenshot).
